name: publish

on: [push]

jobs:

  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/alan-forbes-cp/hello-docker-gcr-demo:latest
        docker run ghcr.io/alan-forbes-cp/hello-docker-gcr-demo:latest
        docker push ghcr.io/alan-forbes-cp/hello-docker-gcr-demo:latest
